spring:
  application:
    name: aggregation-worker

server:
  port: ${SERVER_PORT:8083}

grpc:
  client:
    videoService:
      address: static://${VIDEO_GRPC_HOST:localhost}:${VIDEO_GRPC_PORT:9091}
      negotiationType: plaintext
    playlistService:
      address: static://${PLAYLIST_GRPC_HOST:localhost}:${PLAYLIST_GRPC_PORT:9092}
      negotiationType: plaintext

app:
  jobs:
    trending:
      fixed-delay-ms: ${TRENDING_JOB_DELAY_MS:600000}
