# ========================
# DATABASE CONFIGURATION
# ========================
spring.datasource.url=jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.application.name=S28

# Application version (keep in sync with pom.xml <version>)
app.version=SAMS-01

# ========================
# SERVER
# ========================
server.port=8080
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR

# Silence or reduce OpenTelemetry noise
logging.level.io.opentelemetry=ERROR
logging.level.io.opentelemetry.exporter.internal.grpc.GrpcExporter=OFF
logging.level.io.opentelemetry.instrumentation.spring.autoconfigure=ERROR
spring.jpa.open-in-view=false