apiVersion: v1
kind: Service
metadata:
  name: aggregation-worker
  namespace: youtube-demo
spec:
  selector:
    app: aggregation-worker
  ports:
    - name: http
      port: 8083
      targetPort: 8083
