spring:
  profiles:
    active: local
  application:
    name: playlist-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/playlist_service_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
server:
  port: ${SERVER_PORT:8082}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9092}
  client:
    videoService:
      address: static://${VIDEO_GRPC_HOST:localhost}:${VIDEO_GRPC_PORT:9091}
      negotiationType: plaintext
