apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  namespace: youtube-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: youtube/video-service:local
          ports:
            - containerPort: 8081
            - containerPort: 9091
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: GRPC_SERVER_PORT
              value: "9091"
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/video_db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
