apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: youtube-demo
spec:
  selector:
    app: video-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9091
      targetPort: 9091
